### ISSUE TITLE
Configuration Does Not Save

### ISSUE THREAD

**Issue by daypxl** [octarine-noise/BetterFoliage#67]
Version 2.0.12b for MC 1.9.4 does not save changes to the configuration file when the game is restarted, with the exception of extra leaves.

**Comment by CrazyManLabs** [comment]
Same problem here.
MC-1.9.4
Forge-12.17.0.1987
BetterFoliage-2.0.12b

**Comment by 63502** [comment]
Same with me. I can get the config file to save for one game by regenerating the config file before starting and then changing the settings in mod option on the menu screen, but its really finicky, and it doesn't always work.

Edit: 
I absolutely have to delete and regen the config file every time, otherwise when I open a world, I get about 3 fps.

MC-1.9.4
Forge-12.17.0.1976
BetterFoliage-2.0.12b

**Comment by octarine-noise** [comment]
Fixed in 2.0.13

**Comment by UmbraDominus** [comment]
It is not fixed. Have the latest version and the configurations still do not stay. they revert to default the moment I exit the menu.

**Comment by Lamigo** [comment]
I'm having the same issue than UmbraDominus. When I select true to enable reeds in somes specific biomes, each time as I exit the menu it switch to false.
However switching round logs on and off works.
